<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "wh_animal_collection"
 *
 * Auto generated by Extension Builder 2016-03-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF["bdm_smtp_disable_verify_peer"] = array(
	'title' => 'bdm_smtp_disable_verify_peer',
	'description' => '',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '10.4-11.4.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
